### POST request to example server
GET http://localhost:3000/bids
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pY2hhZWxqYWNrc29uIiwicm9sZSI6InVzZXIiLCJpZCI6MSwiaWF0IjoxNzM0MTk3MDk5fQ.a0U7ceegDAASS2e0KT_jy0-YyLjWiY7xF1rAVGfsAD4
Content-Type: application/json

### POST request to example server
POST http://localhost:3000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pY2hhZWxqYWNrc29uIiwicm9sZSI6InVzZXIiLCJpZCI6MSwiaWF0IjoxNzM0MDQ5MzEwfQ.XZ5dqBCrfD4XPsIJoJs8GZOTzMaJl7vrOqaGfufqeGI
Content-Type: application/json


### POST request to example server
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "michaeljackson",
  "password": "password"
}
### POST request to example server
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "milan",
  "password": "password"
}

### POST request to example server
POST http://localhost:3000/bids
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pY2hhZWxqYWNrc29uIiwicm9sZSI6InVzZXIiLCJpZCI6MSwiaWF0IjoxNzM0MjA0MTEzfQ.RaxSwfz__XZ5fASpZ5Y4gAFH51SE3gIlT8jUPk3pChU
Content-Type: application/json

{
  "listingId": 1,
  "bidAmount": 10002
}